### ISSUE TITLE
Map detail page - Created and Last Modified dates

### ISSUE THREAD

**Issue by sgnewson** [WhyJustRun/Clubsite#164]
From discussion with the FWOC users of Clubsite:

The Created and Last Modified date rows in the Statistics table of the map information page are confusing. They expected the dates to be the dates the map was created and updated, not the dates the file was uploaded or modified.

They have no use for the dates the file was uploaded or modified. So we are wondering if any of the other clubs use these values. If not we would like to remove them, or change them to show dates manually entered by the person uploading the map file.

Action item:
1) find out if any clubs would miss these lines if they were removed or changed.

Proposed changes: 
1) either, remove these lines from the Statistics table
2) or, change these lines to show dates manually entered by the person uploading the map. 

For simplicity I would propose only making these changes to all clubsites or none, instead of adding an administration option to pick between two systems.

**Comment by russellporter** [comment]
Hi Scott,

I think it is fine for to remove the existing dates from the UI for all clubs. I've heard similar complaints from other clubs so I am confident no one will miss them. Lets leave the data in the database though - it is pretty typical to have created/modified dates stored in CMS's anyways.

You could add new columns for user entered created and/or updated dates if you like. It's up to you.

Maybe make the first change (removing the dates from the UI) as a Github Pull Request to this repository, then I can review it (code reviews are a common practice in software companies that I would like to start doing for WhyJustRun too) and we can release it to production.

Then if you want to add the user entered dates, you can do that as a second change.

It's up to you anyways, I think your proposed changes are very reasonable. :)

Cheers,
Russell

**Comment by sgnewson** [comment]
I have a commit that removes those two lines from the table in the Maps view. 
Can you give me commit access on the github repository to push them.

**Comment by russellporter** [comment]
Hey Scott,




Thanks so much for this! Can you submit the commit as a pull request? You don't need push rights to do that, and I would like to try to start reviewing code for WhyJustRun :)

**Comment by sgnewson** [comment]
Ok, there should be a pending pull request now.

**Comment by russellporter** [comment]
Now to push your changes to the production website, just run the deploy_all.sh command (in the google doc) :)

**Comment by sgnewson** [comment]
Done
