### ISSUE TITLE
Events Overlapping End of Month Calendar Bug

### ISSUE THREAD

**Issue by xc-racer3** [WhyJustRun/Clubsite#175]
Any event that runs over the end of a month fails to display on the WhyJustRun Clubsite "Calendar" page on the month that it wraps into.
For example, the Black Forest event (scheduled for May 30th to June 6th) appears just fine on the [Month of May Calendar Page](https://sage.whyjustrun.ca/events/index/01-05-2021), but fails to show up at all on the [Month of June Calendar Page](https://sage.whyjustrun.ca/events/index/01-06-2021) because it wraps over from the previous month.  All events that occur during a given month should be shown on the calendar, not just those starting during that month.

While this would normally be a niche issue, with lots of clubs having week long self-directed trainings at the moment due to COVID, this bug is a fairly regular occurrence.

**Comment by russellporter** [comment]
Thanks for reporting. Deployed the fix now
