### ISSUE TITLE
Thumbnail Course Maps Display Issue (PDF Only)

### ISSUE THREAD

**Issue by xc-racer3** [WhyJustRun/Clubsite#176]
When an event course map is uploaded as a PDF, an image thumbnail is generated for display on the event page, but this thumbnail generation is no longer working properly.

Anywhere a colour is not assigned in the PDF, the thumbnail generator assigns a black colour, instead of an alpha or white colour, which makes the map thumbnails illegible and visually jarring.  For example, see this year's Lynn Valley Adventure Run event page and course map thumbnails: https://gvoc.whyjustrun.ca/events/view/4460

There do no appear to be any display issues when uploading course maps as image file types (I haven't tested all allowed image formats though).  The original PDFs also work just fine (by viewing them after clicking on the thumbnail), it is just an issue with the thumbnail generation.

**Comment by russellporter** [comment]
@xc-racer3 thanks for reporting this. The bug is fixed and I've regenerated the thumbnails of all the courses/maps on WhyJustRun.
